version: '3.8'

services:

#  clickhouse_tot_server:
#    container_name: clickhouse_tot
#    image: yandex/clickhouse-server
#    restart: always
#    env_file:
#      - bd.env
#    #    volumes:
#    #      - "./clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql"
#    ports:
#      - "8123:8123"
#      - "9000:9000"
#      - "9009:9009"
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 262144
#        hard: 262144
  postgres_tot_server:
    image: postgres:latest
    container_name: postgres_tot
    restart: always
    env_file:
      - bd.env
    ports:
      - '5432:5432'
    expose:
      - "5432"
    volumes:
      - ./data:/var/lib/psql/data